### PR TITLE
Update tag name from text-to-image-synthesis to text-to-image

### PR DESCRIPTION
**Pull request by hiveer**
Update tag name from text-to-image-synthesis to text-to-image for both Model and Dataset

### CODE REVIEW

**Review by zhendi — APPROVED** [review]
LGTM

**Comment by ymh6315431** [comment]
LGTM

**Comment by zzxr6** [comment]
LTGM

**Review by ymh6315431 — APPROVED** [review]
LGTM

**Review by zzxr6 — APPROVED** [review]
LGTM

**Pull request merged**
