### PR TITLE
docs: add Japanese README

### PR DESCRIPTION
**Pull request by eltociear**
I created Japanese translated README.

### CODE REVIEW

**Comment by Rader** [comment]
need  someone knows Japanese to help review

**Comment by KinglyWayne** [comment]
I have checked this PR. This translation is awesome. Thank you eltociear for your contribution :)

**Review by KinglyWayne — APPROVED** [review]
LGTM

**Comment by samchen8008** [comment]
@eltociear is that possible to know which company you are at?

**Comment by samchen8008** [comment]
> @KinglyWayne Thank you for your review!
> 
> 
> 
> @samchen8008 Yes it is ok! It will be Oshibloom and I-Tecnology.

Sounds great. Looking for the cooperation in the future. And we are looking for a partner to help with for Japan market. Hope you have a great experience in using our community edition and further more feedback from you. Happy weekend.

**Pull request merged**
