### PR TITLE
模型溯源信息展示

### PR DESCRIPTION
**Pull request by zzxr6**
模型溯源信息展示

### CODE REVIEW

**Review by hiveer — APPROVED** [review]
LGTM

**Comment by hiveer** [comment]
@zzxr6 merge conflicts

**Comment by zzxr6** [comment]
> @zzxr6 merge conflicts

done

**Comment by hiveer** [comment]
@zzxr6 more conflicts need to be resolved

**Comment by zzxr6** [comment]
> @zzxr6 more conflicts need to be resolved

@hiveer done

**Review by hiveer — APPROVED** [review]
LGTM

**Pull request merged**
