### PR TITLE
fix: nginx 50x.html path

### PR DESCRIPTION
**Pull request by CheinTian**
wrong path for 50x.html

### CODE REVIEW

**Comment by CheinTian** [comment]
后端服务器返回50x时，nginx error 如下：

` connect() failed (111: Connection refused) while connecting to upstream, client: 198.19.249.3, server: 198.19.249.163, request: "GET
 / HTTP/1.1", upstream: "http://172.21.0.3:3000/", host: "198.19.249.163"`

**Comment by hiveer** [comment]
@wayneliu0019 please help to do the code review

**Comment by wayneliu0019** [comment]
that's right! 

Thanks @CheinTian

**Review by wayneliu0019 — APPROVED** [review]
LGTM

**Pull request merged**
